name: Build and Publish image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./web-hello -t tomaszbedina/nodejstest:latest
    - name: Push to docker hub
      run: |
        docker login -u tomaszbedina -p ${{ secrets.D_TOKEN }}
        docker push tomaszbedina/nodejstest:latest

